sudo: required

language: r
cache: packages

addons:
  apt:
    packages:
      - pandoc
      - libxml2-dev
r:
  - release

env:
  - SCIDB_VER=18.1-ext

services:
  - docker

before_install:
  - docker pull rvernica/scidb:${SCIDB_VER}
  - docker run
    --name scidb
    --detach
    --volume /dev/shm
    --tmpfs /dev/shm:exec
    --publish 8080:8080
    --publish 8083:8083
    rvernica/scidb:${SCIDB_VER}
  - while ! curl http://localhost:8080/version; do sleep 1; done

r_binary_packages:
  - roxygen2
  - knitr
  - bit64
  - curl
  - data.table
  - openssl
  - devtools
  - tidyr
  - dplyr
  - yaml-
  - reshape2
  - jsonlite
  - testthat

bioc_packages:
  - Biobase
  
r_github_packages:
  - paradigm4/scidb
  
install:
#  - R -e "source('http://bioconductor.org/biocLite.R'); biocLite(c('Biobase'), ask = FALSE);"
#  - R -e "install.packages(c('roxygen2', 'knitr', 'bit64', 'curl', 'data.table', 'openssl', 'devtools', 'tidyr', 'dplyr', 'yaml', 'reshape2', 'jsonlite', 'scidb', 'testthat'))"
  - R -e 'devtools::install_deps(dep = T)'

script:
  - R CMD build .
  - R CMD INSTALL *tar.gz
  - R -e "devtools::test()"

# after_install:

after_failure:
  - docker logs scidb
