---
title: "SciDB pan-study repository Software stack"
output: pdf_document
---

```{r include = FALSE}
knitr::opts_chunk$set(eval=FALSE)
```

# Security

The API assumes the following:
- SciDB EE (enterprise edition) is installed. 
(Install instructions are [here](https://downloads.paradigm4.com/enterprise/16.9/SciDB-Installation-v16.9.pdf).
Contact support@paradigm4.com for login credentials)
- Data can be stored in up to three security namespaces -- 
'public', 'collaboration' and 'clinical'. ('public' is available 
by default; and at least one more namespace must exist)

Follow the steps below to set up the security settings for the API to work:

1. Turn on security for SciDB by following instructions at
https://paradigm4.atlassian.net/wiki/display/ESD169/More+Info
2. Set up the root user (instructions at 
https://paradigm4.atlassian.net/wiki/display/ESD169/Setting+up+the+Root+User)

At this point, you should be able to run the following:
```{sh}
iquery --auth-file ~/.scidb_root_auth -aq "show_user();"
iquery --auth-file ~/.scidb_root_auth -aq "list()"
iquery --auth-file ~/.scidb_root_auth -aq "list('libraries')"
```

We create one of the two possible security namespaces:
```{sh}
iquery -aq "create_namespace('collaboration')"
```

3. Use the following trick to bypass the `auth-file` parameter:

Open a config file:
```{sh}
vi ~/.config/scidb/iquery.conf
# Paste the following there
############################
{
"auth-file":"/home/scidb/.scidb_root_auth"
}
############################
```

At this point, you should be able to run:

```{sh}
iquery -aq "list('libraries')"
```

# Plugins

The plugins and API can be downloaded and installed via any directory, but a 
standard directory structure is currently being used for development.

```{sh}
mkdir -p ~/coding/downloads/plugins
```

Download the scidb4gh API
```{sh}
cd ~/coding/downloads/
# On Ubuntu
git clone https://github.com/Paradigm4/scidb4gh.git
# On Centos
git clone https://<USERNAME>@github.com/Paradigm4/scidb4gh.git
# Contact support@paradigm4.com for access to this repo
```

Download the SciDB plugins
```{sh}
cd ~/coding/downloads/plugins/
git clone https://github.com/Paradigm4/dev_tools.git
```

Next follow [instructions](https://github.com/Paradigm4/dev_tools)
for installing dev_tools. Then load the following libraries:

```{sh}
LIBS_TO_INSTALL="grouped_aggregate accelerated_io_tools equi_join sg_free_cross_between limit summarize"
ALL="10.0.20.185 10.0.20.186 10.0.20.187 10.0.20.184"
# Using dev_tools
# Assuming that dev_tools is already installed
LIBS_TO_INSTALL="grouped_aggregate accelerated_io_tools equi_join sg_free_cross_between limit summarize"
for lib in $LIBS_TO_INSTALL; 
  do
  echo $lib
  iquery -aq "install_github('Paradigm4/$lib')"
  iquery -aq "load_library('$lib')"
done
```

# Shim

Follow instructions at the [P4 Github page](https://github.com/paradigm4/shim). 
Shim is configured using a file under `/var/lib/shim/conf`. 
Importantly, we set `aio=1` in that file for faster download of data from SciDB 
(remember to restart SciDB at this point)

```{sh}
sudo service shimsvc restart
```

# Package installation

First the dependencies

```{sh}
# Ubuntu
sudo apt-get install libxml2-dev
# Centos
sudo yum install libxml2-dev # need the Centos equivalent here (auto-prompted by R roxgen2 install below)
```

Next, install the following R packages from CRAN
```{sh}
sudo R
# Then run
install.packages(c('roxygen2', 'tidyr', 'RPostgreSQL')); 
source("http://bioconductor.org/biocLite.R"); 
biocLite(c("Biobase")); 
```

Next we install the SciDB-R package (we can also install from CRAN). Below,
we show how to install via devtools:
```{sh}
sudo R --slave -e "devtools::install_github('Paradigm4/scidbr')"
```


Finally the API install (assuming the directory choice described above):

```{sh}
USER=scidb
pushd /home/$USER/coding/downloads/scidb4gh/; R --slave -e "library(roxygen2); roxygenize()" && cd .. && sudo R CMD build scidb4gh && sudo R CMD INSTALL scidb4gh_0.1.tar.gz ; popd
```

# Package setup and usage

Password (just for demo purposes)

```{sh}
vi ~/ga4gh-config.R
# Put in the following there
#######
CODEPATH = '~/coding/jnj/sow2/load'
rootpassword="Paradigm4"
#######
```

Now let us get to using the package:

```{R}
library(scidb4gh)
gh_connect('root', 'Paradigm4')
init_db(arrays_to_init = 'ONTOLOGY')           # CAUTION: To be used with care by DB admin only
init_db(arrays_to_init = get_entity_names())   # EXTREME CAUTION: To be used with extreme care by DB admin only
```


