rm(list=ls())
library(revealgenomics)
options(scidb.result_size_limit = 4096)
##-----------------------------------------------------------------------------------------------##
# This script calls search_biosamples() and search_expression() and records the run time time
# for each of these calls.
# Log files generated by this script are saved at './data/log_raw/' as runTime_YYYYmmdd.txt.
# Run time records are saved at './data/raw/' as runTime_YYYYmmdd.csv

##-----------------------------------------------------------------------------------------------##
#### Login and download datasets and measurementset ####

## Login
creds_file = '~/.scidb_secure_user_auth'
rg_connect(username = read_json(creds_file)$`user-name`, 
           password = read_json(creds_file)$`user-password`)

## get all the datasets (dataset_id is unique here?)
dat = get_datasets()

## get information about all the pipelines (measurement_id is unique here?)
ms = get_measurementsets()
ms <- drop_na_columns(ms[ms$entity == 'RNAQUANTIFICATION',])

####---------------------------------------------------------------------------------------------####
#### Utility functions to measure run time ####

#------------------------------------------------#
# get_compute_time()
# This function calls functions search_biosamples() and search_expression() and records the
# run time of these functions.
# This function writes all outputs to a log file.
#
# INPUT:
# msi_dataset_id: A dataset_id from get_datasets().
# msi_measurementset_id: A measurementset_id from get_measurementsets().
# branch: revealgenomics branch being currently used.
# verbose: To receive run time messages. The default value is set as TRUE.
# logger: If output should written to a log file. The default value is set as TRUE.
# logger_filePath: log file path if 'logger' is set as TRUE.
#
# OUTPUT:
# A list with branch name, run time for search_biosamples() and search_expression(), and size of 
# the object returned by get_biosamples() and search_experimentsets().
# If logger is set as TRUE then logs are wriiten to logger_filePath
#
# For a vectorised version of this function please use the function repear_runs().
# The mark #---HC---# is used to indicate a hardcoding and requires attention if datasets 
# are changed.

get_compute_time <- function(msi_dataset_id, msi_measurementset_id, branch, verbose = TRUE, 
                             logger = TRUE, logger_filePath) {
  
  msi = drop_na_columns(ms[which((ms$dataset_id %in% msi_dataset_id) &                             #---HC---#
                                   (ms$measurementset_id %in% msi_measurementset_id)),])           #---HC---#
  d_sel = drop_na_columns(dat[which(dat$dataset_id %in% msi$dataset_id),])                         #---HC---#

  if(verbose) {
    message("--------------------------------------------------------------------------------\n",
            "Working on:\n", 
            "\tdataset_id: ", msi$dataset_id, ", dataset_name: ", d_sel$name,                      #---HC---#
            "\n\tmeasurementset_id: ", msi$measurementset_id, ", measurementset_name: ", msi$name) #---HC---#
  }
  
  ## create output object
  ret <- list(branch = branch,
              biosample_down_time_sec = NA, biosample_size = NA, 
              expression_down_time_sec = NA, exp_size = NA)
  ret$ds_name <- d_sel$name; ret$ds_id <- d_sel$dataset_id
  ret$ms_name <- msi$name; ret$ms_id <- msi$measurementset_id
  
  ## log
  if(logger) {
    if(!file.exists(logger_filePath)) {
      cat(paste('branch:', branch, '|',
                'ds_name:', d_sel$name, '|', 'ds_id :', d_sel$dataset_id, '|', 
                'ms_name:', msi$name, '|', 'ms_id:', msi$measurementset_id, '\n', sep = ''), 
          file = logger_filePath, append = FALSE)
      logFile = file(logger_filePath, open = 'at')
      sink(file = logFile, append = TRUE, type = 'output')
      sink(file = logFile, append = TRUE, type = 'message')
    } else {
      logFile = file(logger_filePath, open = 'at')
      sink(file = logFile, append = TRUE, type = 'output')
      sink(file = logFile, append = TRUE, type = 'message')
      cat(paste('branch:', branch, '|',
                'ds_name:', d_sel$name, '|', 'ds_id :', d_sel$dataset_id, '|', 
                'ms_name:', msi$name, '|', 'ms_id:', msi$measurementset_id, '\n', sep = ''), 
          file = logFile, append = TRUE)
    }
  }
  
  ##-------------------------
  if(logger) {
    cat('search_biosamples() - \n', file = logFile, append = TRUE)
  }
  
  ## download biosamples
  ret$biosample_down_time_sec = system.time(
    {bios_ref = search_biosamples(dataset_id = msi$dataset_id)})[[3]]
  ret$biosample_size = format(object.size(bios_ref), units = 'Mb')
  
  if(logger) {
    cat(paste('time (Sec):', ret$biosample_down_time_sec, '\n',sep=' '), file = logFile, 
        append = TRUE)
    cat(paste('size (Mb):', ret$biosample_size, '\n', sep = ' '), file = logFile, 
        append = TRUE)
  }
  
  ##-------------------------
  if(logger) {
    cat('search_expression() - \n', file = logFile, append = TRUE)
  }
  
  ## download expression data
  try({
    ret$expression_down_time_sec = system.time({
      exp_set = search_expression(measurementset = msi, biosample_ref = bios_ref)})[[3]]
    ret$exp_size <- format(object.size(exprs(exp_set)), units = 'Mb')
  })
  
  if(logger) {
    cat(paste('time (sec):', ret$expression_down_time_sec, '\n', sep = ' '), file =logFile,
        append=TRUE)
    cat(paste('size (Mb):', ret$exp_size, sep = ' '), file = logFile, append = TRUE)
    cat(paste('\n', paste(rep('-', 50), collapse = ''), '\n', sep = ''), file = logFile, 
        append = TRUE)
  }
  closeAllConnections()
  
  ##-------------------------
  return(ret)
}

#------------------------------------------------#
# repeat_runs()
# This function is a wrapper function for get_compute time.
# This function writes the run time and size of returned object of search_biosamples() and 
# search_expression()
#
# INPUT:
# repeat_run: The number of times search_biosamples() and search_expression() should be called a 
# particular study. dataset_id and measurementset_id are used and keys for identifying studies.
# Branch: revealgenomics branch being currently used.
# reprunAppend: If the output from get_compute_time() i.e. run time data should be append-ed 
# to an existing file (if it exists).
# write_to_file: If the run time and size of returned object of search_biosamples() and 
# search_expression() should be written to a file.
# write_to_file_fp: If write_to_file is TRUE then file path to write run time and object size data.
# row_num: The number of rows/studies of get_measurementsets() data for which run time data from 
# search_biosamples() and search_expression() is required.
# Verbose: To receive run time messages. The default value is set as TRUE.
# Logger: If output should written to a log file. The default value is set as TRUE.

# OUTPUT:
# run time and object size are returned as a data.frame with the following structure -
#  $ branch                  : chr  
#  $ biosample_down_time_sec : num  
#  $ biosample_size          : chr   
#  $ expression_down_time_sec: num  
#  $ exp_size                : chr  
#  $ ds_name                 : chr  
#  $ ds_id                   : int  
#  $ ms_name                 : chr  
#  $ ms_id                   : int  
# If logger is set as TRUE then a log is written to a modified write_to_file_fp and 
# if write_to_file is set as TRUE then the above output is wriiten to write_to_file_fp.
#
# The file path provided for write_to_file_fp is modified from /data/raw to /data/log_raw and
# the extension is changed from .csv to .txt for writting log.
# The mark #---HC---# is used to indicate a hardcoding and requires attention if datasets 
# are changed.

repeat_runs <- function(repeat_run, Branch, reprunAppend, write_to_file, write_to_file_fp, row_num, 
                        Verbose, Logger) {

  write_to_log_fp = sub(pattern = '/raw/', replacement = '/log_raw/', x = write_to_file_fp)
  write_to_log_fp = sub(pattern = 'csv', replacement = 'txt', x = write_to_log_fp)
  run_time = mapply(x = as.list(rep(ms$dataset_id[1:row_num], repeat_run)),                        #---HC---#
                    y = as.list(rep(ms$measurementset_id[1:row_num], repeat_run)),                 #---HC---#
                    FUN = function(x, y) unlist(get_compute_time(msi_dataset_id = x,
                                                                 msi_measurementset_id = y, 
                                                                 verbose = Verbose,
                                                                 branch = Branch,
                                                                 logger = Logger,
                                                                 logger_filePath = write_to_log_fp)),
                    SIMPLIFY = FALSE)
  run_time = as.data.frame(do.call(rbind, run_time), stringsAsFactors = FALSE)

  if(write_to_file) {
    if(reprunAppend) {
      write.table(run_time, file = write_to_file_fp, append = TRUE, row.names = FALSE, 
                  col.names = FALSE, sep = ',')
    } else {
      write.table(run_time, file = write_to_file_fp, row.names = FALSE, sep = ',', append = FALSE)
    }
  }
  
  return(run_time)
}

####-------------------------------------------------------------------------------------------####
#### get run time ####
# Run time data returned by this script is saved at ./data/raw. The naming convention used for run 
# time data is runTime_YYYYmmdd.csv
# Log data is saved at ./data/log_raw. The naming convention used for log file is 
# runTime_YYYYmmdd.txt

run_time = repeat_runs(repeat_run = 6, row_num = nrow(ms), Branch = 'dt_enc_v2',                  ##---Change per run---##
                       write_to_file = TRUE, reprunAppend = TRUE,                                 ##---Change per run---##
                       Verbose = FALSE, Logger = TRUE,
                       write_to_file_fp = paste('/home/arko/coding/revealgenomics/custom_scripts/',
                                                'run-time-comparison-between-branches/data/raw/',
                                                'runTime_20190730.csv', sep = ''))
# Branches used and their names - 
# master - master
# data.table_enhancements_v2 - dt_enc_v2
# 
# A sample output -
# head(run_time)
#   branch biosample_down_time_sec biosample_size expression_down_time_sec exp_size   ds_name ds_id         ms_name ms_id
# 1 master                   0.724         0.3 Mb                   15.076  69.2 Mb TCGA-LAML     1 HTSeq - FPKM-UQ     1
# 2 master                   0.803         0.3 Mb                   13.923  69.2 Mb TCGA-LAML     1    HTSeq - FPKM     2
# 3 master                   0.817         0.3 Mb                   15.406  69.2 Mb TCGA-LAML     1  HTSeq - Counts     3
# 4 master                   0.727         0.2 Mb                   12.305  38.1 Mb  TCGA-ACC     2 HTSeq - FPKM-UQ    34
# 5 master                   0.789         0.2 Mb                   10.562  38.1 Mb  TCGA-ACC     2    HTSeq - FPKM    35
# 6 master                   0.861         0.2 Mb                   10.335  38.1 Mb  TCGA-ACC     2  HTSeq - Counts    36
